services:
  docker-nzbget:
    container_name: docker-nzbget
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile.dev
    restart: "no"
    env_file: .env
    networks:
      - docker-nzbget-network
    volumes:
      - ${HOME}/.config/gh:/home/vscode/.config/gh
      - ${HOME}/.ssh:/home/vscode/.ssh
      - ${HOME}/.zhistory:/home/vscode/.zhistory
# Networks to be created to facilitate communication between containers
networks:
  docker-nzbget-network:
    driver: bridge
